import csv
import matplotlib.pyplot as plt
import os
import math
import pandas as pd
import json

def debug_show_ep_results():
    
    script_dir = os.path.dirname(__file__)
    project_root = os.path.dirname(script_dir)
    result_dir = os.path.join(project_root, 'output')
    result_file = os.path.join(result_dir, 'eplusout.csv')

    #generated by gemini
    temp = []

    with open(result_file, 'r') as csvfile:
        temp = get_csv_data(result_file,"MAIN:Zone Mean Air Temperature [C](Hourly)")[:24]

    # Create the line plot
    plt.figure(figsize=(12, 7)) # Slightly larger figure for two lines
    
    # Plot Column 2
    if temp:
        plt.plot(temp, marker='o', linestyle='-', label="room_temperature")
    


    plt.title(f'First 24 Values from {result_file.split(os.sep)[-1]}')
    plt.ylabel('Values')
    plt.grid(True)
    plt.legend() # Show the legend for multiple series
    plt.tight_layout() # Adjust layout to prevent labels from overlapping
    plt.show()
    
    return 0
def extract_ep_results(inputJSON):
    script_dir = os.path.dirname(__file__)
    project_root = os.path.dirname(script_dir)
    result_dir = os.path.join(project_root, 'output')
    result_file = os.path.join(result_dir, 'eplusout.csv')
    output_file_path = os.path.join(result_dir, 'output.json')
    gfa = inputJSON["gfa"]
    COP = inputJSON["COP"]

    annual_cooling_demand = round(sum(get_csv_data(result_file,"DistrictCooling:Facility [J](Hourly)"))*2.78*math.pow(10,-7)/gfa,2)
    annual_cooling_electricity = round(annual_cooling_demand/COP,2)
    annual_lighting_electricity = round(sum(get_csv_data(result_file,"InteriorLights:Electricity [J](Hourly)"))*2.78*math.pow(10,-7)/gfa,2)
    annual_equipment_electricity = round(sum(get_csv_data(result_file,"InteriorEquipment:Electricity [J](Hourly)"))*2.78*math.pow(10,-7)/gfa,2)
    annual_lift_electricity = 0
    annual_carpark_electricity = 0
    annual_outdoor_lighting_electricity = 0
    annual_total_electricity = annual_cooling_electricity + annual_equipment_electricity +annual_lighting_electricity+ annual_lift_electricity + annual_carpark_electricity + annual_outdoor_lighting_electricity
    annual_occupied_hours = 0
    max_electricity_demand = 0
    max_cooling_demands = round(max(get_csv_data(result_file,"DistrictCooling:Facility [J](Hourly)"))*2.78*math.pow(10,-7),2)
    
    output= {
        "cooling_electricity":annual_cooling_electricity,
        "cooling_consumption":annual_cooling_demand,
        "lighting_electricity":annual_lighting_electricity,
        "equipment_electricity":annual_equipment_electricity,
        "lift_electricity": annual_lift_electricity,
        "carpark": annual_carpark_electricity, 
        "outdoor_facade_lighting":annual_outdoor_lighting_electricity,
        "total_electricity":annual_total_electricity,
        "max_electricity_demand": max_electricity_demand,
        "max_cooling_demand": max_cooling_demands,
        "occupied_hours":annual_occupied_hours
    }
    with open(output_file_path, 'w') as output_file:
        json.dump(output, output_file,indent=2)
    
    
    return 0
#debug_show_ep_results()

def get_csv_data(csv_path,header):
    df = pd.read_csv(csv_path)
    return df[header].tolist()